appName: com.github.ohbaron.dropwizardkotlinexamplev1

server:
  requestLog:
    appenders:
      - type: console
      - type: file
        currentLogFilename: logs/access.log
        threshold: ALL
        archive: true
        archivedLogFilenamePattern: logs/access.%d.log.gz
        archivedFileCount: 5
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO
  appenders:
    - type: console
    - type: file
      currentLogFilename: logs/com.github.ohbaron.dropwizardkotlinexamplev1.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: logs/com.github.ohbaron.dropwizardkotlinexamplev1-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC